Add touch events fixes and e2e tests
ZeaInc/zea-ux pull request #85
Opened 2020-09-22 17:20 UTC by apajaro

2020-09-25 12:21 UTC, mauroporras commented
Looks like a WIP. Converted to draft.

2020-10-08 20:52 UTC, mauroporras requested changes
Let's fix conflicts first.

2020-10-08 20:52 UTC, mauroporras commented on package.json
> +    "npm-run-all": "^4.1.5"
This one needs to be a dev dep.

2020-10-16 20:11 UTC, apajaro commented
There's an issue with iOS devices that doesn't allow selection of the right geometries on Selection tool.
This has to do with the changes introduced in the `StandardSurfaceGeomDataShader` class for `UInt8 buffer`.

2020-10-20 13:40 UTC, phtaylor commented
> There's an issue with iOS devices that doesn't allow selection of the right geometries on Selection tool.
> This has to do with the changes introduced in the `StandardSurfaceGeomDataShader` class for `UInt8 buffer`.
> 
> @phtaylor

this is fixed now. Lets get the conflicts resolved and merge this as soon as possible.

2020-10-20 13:40 UTC, phtaylor commented
Note: I changed the handle size, so this may effect the e2e tests. I'm not sure why the appeared so huge for me.

2020-10-20 14:14 UTC, phtaylor approved these changes

2020-10-20 19:04 UTC, closed without merging